# Generated by Django 3.2 on 2023-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kwitantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwitantienummer', models.CharField(default='', max_length=20)),
                ('bedrag', models.IntegerField(default=0)),
                ('aantal_uren', models.CharField(default='', max_length=20)),
                ('project', models.CharField(default='', max_length=200)),
                ('beschrijving', models.CharField(default='', max_length=700)),
                ('dienst', models.CharField(default='', max_length=40)),
                ('naam', models.CharField(max_length=200)),
                ('straat', models.CharField(default='', max_length=200)),
                ('nummer', models.CharField(default='', max_length=20)),
                ('toevoeging', models.CharField(blank=True, default='', max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('plaats', models.CharField(max_length=100)),
                ('land', models.CharField(default='Nederland', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarief',
            fields=[
                ('bedrag', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('naam', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
